### ISSUE TITLE
kube-rbac-proxy in k8s deployment file is outdated and has CVEs

### ISSUE THREAD

**Issue by lreed-mdsol** [nekomeowww/ollama-operator#13]
The current kube-rbac-proxy in k8s deployment file is outdated and has CVEs
I created a PR to fix this.
https://github.com/nekomeowww/ollama-operator/pull/12

kube-rbac-proxy:v0.15.0 -> kube-rbac-proxy:v0.18.0

Thanks!

**Comment by nekomeowww** [comment]
Close as completed.
