### ISSUE TITLE
Support for specifying runtimeClassName in model resource

### ISSUE THREAD

**Issue by travnewmatic** [nekomeowww/ollama-operator#15]
Not sure sure if i'm doing something wrong or theres an easier workaround for this.

I'm using the nvidia gpu operator in a very vanilla config.

This results in the generation of several `runtimeClass` resources.

In this configuration, where one component of the nvidia gpu operator is handling the driver instead of me manually installing the driver on the host, it seems that pods which want to have access to the GPU require `runtimeClassName: nvidia` to be in the pod spec.

I'm not sure if I'm missing it or not but I dont see a way to specify `runtimeClassName` in the CRD for a model.  Thanks for all the hard work!  I'd really like to use your project!

**Comment by nekomeowww** [comment]
Hi, thanks for the issue. And thanks for the in-detailed statement.

Indeed, after a brief read through documentations, I found `runtimeClass` requires extra parameters with no workaround (retricted by immutable of Pods, too, so no directly modifications are allowed.)

I will add one for you ASAP today. Stay tuned.
